minimal:
  joint_state_controller:
    type: joint_state_controller/JointStateController
    publish_rate: 100


  left_steering_controller:
    joint: left_steering_joint
    type: effort_controllers/JointPositionController
    pid: {p: 500.0, i: 0.0, d: 0.0}


  right_steering_controller:
    joint: right_steering_joint
    type: effort_controllers/JointPositionController
    pid: {p: 500.0, i: 0.0, d: 0.0}


  left_front_axle_controller:
    joint: left_front_axle
    type: velocity_controllers/JointVelocityController
    pid: {p: 1500.0, i: 100.0, d: 750.0}
      

  right_front_axle_controller:
    joint: right_front_axle
    type: velocity_controllers/JointVelocityController
    pid: {p: 1500.0, i: 100.0, d: 750.0}


  left_rear_axle_controller:
    joint: left_rear_axle
    type: velocity_controllers/JointVelocityController
    pid: {p: 1500.0, i: 100.0, d: 750.0}


  right_rear_axle_controller:
    joint: right_rear_axle
    type: velocity_controllers/JointVelocityController
    pid: {p: 1500.0, i: 100.0, d: 750.0}

#  LocalWords:  JointVelocityController JointPositionController
#  LocalWords:  JointStateContoller
